local Rarities = {
    Common = {
        Weight = 50,
        HealthMultiplier = 1.0,
        DamageMultiplier = 1.0,
        SpeedMultiplier = 1.0,
        KillReward = 10,
        PassiveTickReward = 1,
        PassiveTicks = 20,
        Color = Color3.fromRGB(180, 180, 180),
    },
    Uncommon = {
        Weight = 25,
        HealthMultiplier = 1.35,
        DamageMultiplier = 1.15,
        SpeedMultiplier = 1.05,
        KillReward = 20,
        PassiveTickReward = 2,
        PassiveTicks = 24,
        Color = Color3.fromRGB(100, 220, 120),
    },
    Rare = {
        Weight = 12,
        HealthMultiplier = 1.9,
        DamageMultiplier = 1.35,
        SpeedMultiplier = 1.1,
        KillReward = 45,
        PassiveTickReward = 4,
        PassiveTicks = 25,
        Color = Color3.fromRGB(90, 140, 255),
    },
    Epic = {
        Weight = 7,
        HealthMultiplier = 2.6,
        DamageMultiplier = 1.6,
        SpeedMultiplier = 1.15,
        KillReward = 90,
        PassiveTickReward = 8,
        PassiveTicks = 28,
        Color = Color3.fromRGB(180, 90, 240),
    },
    Legendary = {
        Weight = 4,
        HealthMultiplier = 3.5,
        DamageMultiplier = 2.0,
        SpeedMultiplier = 1.2,
        KillReward = 180,
        PassiveTickReward = 16,
        PassiveTicks = 30,
        Color = Color3.fromRGB(255, 180, 60),
    },
    Mythic = {
        Weight = 2,
        HealthMultiplier = 5.0,
        DamageMultiplier = 2.8,
        SpeedMultiplier = 1.25,
        KillReward = 350,
        PassiveTickReward = 30,
        PassiveTicks = 35,
        Color = Color3.fromRGB(255, 70, 130),
    },
}

return Rarities
